# Question 1

In [38]:
import pandas as pd
import numpy as np
pd.__version__


'1.5.3'

# Question 2

In [47]:
data = pd.read_csv('housing.csv')

In [48]:
len(data.columns)

10

# Question 3

In [49]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4

In [51]:
len(data['ocean_proximity'].unique())


5

# Question 5

In [30]:
mask = data['ocean_proximity'] == "NEAR BAY"

data.loc[mask, 'median_house_value'].mean()

259212.31179039303

# Question 6

In [52]:
total_bedroom_mean = data['total_bedrooms'].mean()
total_bedroom_mean

537.8705525375618

In [53]:
data['total_bedrooms'] = data['total_bedrooms'].fillna(total_bedroom_mean)

In [54]:
data['total_bedrooms'].mean()

537.8705525375617

# Question 7

In [55]:
mask = data['ocean_proximity'] == "ISLAND"

data.loc[mask, ['housing_median_age', 'total_rooms', 'total_bedrooms']]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [39]:
X = np.array(data.loc[mask, ['housing_median_age', 'total_rooms', 'total_bedrooms']])

In [41]:
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [43]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [56]:
y = np.array([950, 1300, 800, 1000, 1300])

In [59]:
w = np.dot(np.dot(inv_XTX, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [61]:
last_elem = w[-1]
last_elem

5.6992294550655656